# Generated by Django 4.0.4 on 2022-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipousuario_alter_suscripcion_is_suscrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='usuarios'),
        ),
    ]
